# Generated by Django 2.2.dev20180916104534 on 2018-09-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoist', '0002_auto_20180917_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
