# Generated by Django 2.1.1 on 2018-09-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoist', '0003_auto_20180917_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='content',
            field=models.TextField(),
        ),
    ]
